### ISSUE TITLE
Date/DatePicker return to old value when entered via keyboard

### ISSUE THREAD

**Issue by dtaksan** [Digiturk/wface#102]

**Comment by mbrn** [comment]
@dtaksan 

Bahsedilen sorun sadece text manuel degistirilip lost focus yapilmadan dialog acilirsa olusuyor sanırım. Onun dısında manuel degisiklikte sorun yok. Simdilik bunu halledemeyiz. WFace versiyon upgrade de sorun cozulecektir diyebiliriz. Bence zaten fatal bir sorun da degil.
