### ISSUE TITLE
Blank page when building the app.

### ISSUE THREAD

**Issue by mastercoks** [Digiturk/wface#54]
**Describe the bug**
When building the static app using the `npm run-script build`, the created page is blank.

**To Reproduce**

1. Generate the new project `wface create project`
2. Change the file `@wface/container/configs/webpack/prod.js`  as the print below:
![image](https://user-images.githubusercontent.com/7410215/61654985-00332580-ac94-11e9-9f30-8f8af23df991.png)
3. Build the app `npm run-script build` 

**Expected behavior**
Build the app successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/7410215/61655250-8ea7a700-ac94-11e9-9108-e1bcf1491a38.png)

PS: The change to the file was made because the app was not finding the file `/js/main.min.js`

**Comment by mastercoks** [comment]
PS2: In version 0.14.1 it is working.

**Comment by mbrn** [comment]
Thanks for issue @mastercoks . I am closing it.

**Comment by mastercoks** [comment]
> Thanks for issue @mastercoks . I am closing it.

In the current version 0.20.0 is not working, or previous.

**Comment by mbrn** [comment]
I will take a look at it asap.

**Comment by mastercoks** [comment]
Any news about this?

**Comment by mbrn** [comment]
Sorry @mastercoks ,

I was working on tight deadline project until 2-3 days ago. I will look at this in a few days. If you have any solution, please feel comfort to send a PR.
