### ISSUE TITLE
Add app cache hook

### ISSUE THREAD

**Issue by dtaksan** [Digiturk/wface#76]

**Comment by mbrn** [comment]
@dtaksan clarification please

**Comment by dtaksan** [comment]
> @dtaksan clarification please

WFace cache'in daha kolay kullanılabilmesi amacı ile cache'e bir hook düzenlenmişti fakat su anlık işlevsiz bulunup kaldırıldı.
Sonraki versiyonlarda tekrar düzenlenebilir.

Teşşekkürler.
