### ISSUE TITLE
BUG: string icons and expand icons are not visible on WTable

### ISSUE THREAD

**Issue by kcocalak** [Digiturk/wface#87]

**Comment by kcocalak** [comment]
![image](https://user-images.githubusercontent.com/29271150/235921757-361070ad-5845-42de-9bc6-2c7b233bdb58.png)

**Comment by mbrn** [comment]
Iconlar bu sekilde kullanılırsa calisiyor. Bu sekilde devam edelim. 

![image](https://user-images.githubusercontent.com/7895451/236630484-e1325146-88d0-4208-a7de-5567d31f3cd1.png)
