### ISSUE TITLE
BUG: if the component is not inside subnodes for the menu drawer, it doesn't work 

### ISSUE THREAD

**Issue by kcocalak** [Digiturk/wface#88]

**Comment by mbrn** [comment]
Örnek bir json data paylaşabilir misin?

Yani getMenuTree'nin sonucunu verebilirsin dogrudan test edebilmem için. 

@kcocalak

**Comment by kcocalak** [comment]
{
          id: 'DemoScreen',
          text: 'DemoScreen',
          screen: 'DemoScreen',
          icon: 'save'
        },
        {
          id: 'DemoScreen2',
          text: 'DemoScreen2',
          screen: 'DemoScreen2',
          subNodes: [
            {
              id: 'DemoScreen3',
              text: 'DemoScreen3',
              screen: 'DemoScreen3',
            },
            {
              id: 'DemoScreen4',
              text: 'DemoScreen4',
              screen: 'DemoScreen4'
            }
          ]
        },
        {
          id: 'DemoScreen5',
          text: 'DemoScreen5',
          screen: 'DemoScreen5'
        },
        {
          id: 'EmptyScreen',
          text: 'EmptyScreen',
          screen: 'EmptyScreen'
        },
        {
          id: 'Settings',
          text: 'Settings',
          screen: 'SettingsScreen2',
          hideOnNavigationList: true
        },
        {
          id: 'Nested2',
          text: 'Nested2',
          // screen: 'SettingsScreen2',
          subNodes: [
            {
              id: 'SubDemoScreen3',
              text: 'SubDemoScreen3',
              screen: 'DemoScreen3'
            },
            {
              id: 'SubDemoScreen4',
              text: 'SubDemoScreen4',
              screen: 'DemoScreen4'
            },
          ]
        }
      ];

**Comment by mbrn** [comment]
@kcocalak bunu cozduk degil mi? Suan calisiyorsa kapatabilir misin?
