### ISSUE TITLE
Feature: multi language support some turkish pages like No-Page,error-page etc.

### ISSUE THREAD

**Issue by kcocalak** [Digiturk/wface#92]

**Comment by kcocalak** [comment]
![image](https://github.com/Digiturk/wface/assets/29271150/516dac61-515a-482f-9877-56ad3a979c20)

**Comment by mbrn** [comment]
0.3.5 versiyonu ile özellik eklendi. Aşagıdaki kod configuration'a eklenerek wface textleri degistirlebilir. Burada react-i18n gibi libraryler cagrilabilir. 

```
 useTranslation: () => {
    return {
      t: (key: string) => key + "Tranlated"
    }
  }
```
