### ISSUE TITLE
Feature: Add Button or Switch on Toolbar for seperated Menus or Pages

### ISSUE THREAD

**Issue by kcocalak** [Digiturk/wface#93]
![image](https://user-images.githubusercontent.com/29271150/236477261-56706fa7-f0ef-4d3c-9ab7-9a6b22c9991d.png)

**Comment by mbrn** [comment]
![image](https://user-images.githubusercontent.com/7895451/236629750-7a812fcd-cd4a-45bb-8360-06d5be1eb861.png)

**Comment by kcocalak** [comment]
@mbrn burda CMS yada CRM butonuyla farkli menulerin cikmasi isteniyor, bunun icin nasil bir yonlendirme yapmamiz gerekiyor? Configde iki farkli menu mu olusturacagiz? Onun icin config yapisi uygun mu?

**Comment by mbrn** [comment]
Ekran görüntüsündeki kodun içinde components ile butonu ekleyebilirsin. Butonu bir contexte baglamamiz lazım. Onu da birlikte Çarşamba günü yapalım.
