### ISSUE TITLE
feature: open default page after login 

### ISSUE THREAD

**Issue by kcocalak** [Digiturk/wface#97]

**Comment by mbrn** [comment]
Burada da yine navigate kullanılarak istenilen sayfaya yonlendirebilirsiniz. 

     Benim sayfaları kapatmam söz konusu degil artık. Cünkü sayfayı url'de alıyor. Bos sayfaya gecmek icin toolbardaki buton click'de sunu yapabilirsin:

```javascript
const navigate = useNavigate();

onClick = () => {
// normalde yaptıgın işler. 

  navigate('/main/DemoScreen3')
// DemoScreen3 yerine ekran id'si kullanılacak.  custom login componenti yazdıysanız onun içinde cagirabilirsiniz. 
}
```
