### ISSUE TITLE
bug: when change the menu from toolbar, before page is not closing. 

### ISSUE THREAD

**Issue by kcocalak** [Digiturk/wface#98]
Maybe after changing we can go to default menu page or we can keep on the cache every menu's page and we can use it

**Comment by mbrn** [comment]
Benim sayfaları kapatmam söz konusu degil artık. Cünkü sayfayı url'de alıyor. Bos sayfaya gecmek icin toolbardaki buton click'de sunu yapabilirsin:

```javascript
const navigate = useNavigate();

onClick = () => {
// normalde yaptıgın işler. 

  navigate('/main')
}
```
